<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhAcidezRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhAcidezRepository extends \Doctrine\ORM\EntityRepository
{
}
