<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhAnalisisSensorialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhAnalisisSensorialRepository extends \Doctrine\ORM\EntityRepository
{
}
