<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhAnalisisMicrobiologicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhAnalisisMicrobiologicoRepository extends \Doctrine\ORM\EntityRepository
{
}
