<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhCrematocritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhCrematocritoRepository extends \Doctrine\ORM\EntityRepository
{
}
