<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhCurvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhCurvaRepository extends \Doctrine\ORM\EntityRepository
{
}
