<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhCtlCentroRecoleccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhCtlCentroRecoleccionRepository extends \Doctrine\ORM\EntityRepository
{
    /////////////////////////////////////////////////////////////////////////////////////
    //////// SEARCH LOCATION METHOD
    /////////////////////////////////////////////////////////////////////////////////////
    public function searchLocation($q)
    {
        $query = $this->getEntityManager()
                    ->createQueryBuilder('t01')
                            ->select('t01')
                            ->addSelect('t01.id AS id, t01.nombre as full_name')
                            ->from('MinsalSiblhBundle:BlhCtlCentroRecoleccion', 't01')
                            ->orderBy('full_name')
                            ->distinct()
                            ->setMaxResults(50);

        $query->where($query->expr()->like('LOWER(t01.nombre)', ':loc_name'))
                            ->setParameter('loc_name', '%' . trim(strtolower($q)) . '%');

        return $query->getQuery()->getScalarResult();
    }

    /////////////////////////////////////////////////////////////////////////////////////
    //////// SEARCH LOCATION BY ID METHOD
    /////////////////////////////////////////////////////////////////////////////////////
    public function searchLocationById($id)
    {
        $query = $this->getEntityManager()
                    ->createQueryBuilder('t01')
                            ->select('t01')
                            ->addSelect('t01.id AS id, t01.nombre as full_name')
                            ->from('MinsalSiblhBundle:BlhCtlCentroRecoleccion', 't01')
                            ->where('t01.id = :id')
                            ->setParameter('id', $id);

        return $query->getQuery()->getScalarResult();
    }
    public function generateCode()
    {
        try {
            $conn   = $this->getEntityManager()->getConnection();

            $sql    = "SELECT LPAD((COALESCE(MAX(CAST(TRIM(LEADING 'CTR-' FROM ctr.codigo) AS INT)), 0) + 1)::text, 2, '0') AS code
                        FROM blh_ctl_centro_recoleccion AS ctr";

            $stmt   = $conn->prepare($sql);
            $stmt->execute();

            $result = $stmt->fetchAll();

            if (is_array($result) && count($result) > 0) {
                return $result[0];
            }
        } catch (Exception $e) {
            return null;
        }
        return null;
    }

}