<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhCurvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhCurvaRepository extends \Doctrine\ORM\EntityRepository
{
    /////////////////////////////////////////////////////////////////////////////////////
    //////// SEARCH BY ID METHOD
    /////////////////////////////////////////////////////////////////////////////////////
    public function searchById($id)
    {
        $query = $this->getEntityManager()
                    ->createQueryBuilder('t01')
                            ->select('t01')
                            ->from('MinsalSiblhBundle:BlhCurva', 't01')
                            ->andWhere('t01.id = :id')
                            ->setParameter('id', $id);

        return $query->getQuery()->getScalarResult();
    }

}