<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhDonacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhDonacionRepository extends \Doctrine\ORM\EntityRepository
{
}
