<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhDonanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhDonanteRepository extends \Doctrine\ORM\EntityRepository
{
    /////////////////////////////////////////////////////////////////////////////////////
    //////// SEARCH METHOD
    /////////////////////////////////////////////////////////////////////////////////////
    public function search($localeId, $t, $q)
    {
        ////////////////////////////////////////
        //////// donor is local
        ////////////////////////////////////////
        $query = $this->getEntityManager()
                    ->createQueryBuilder('t01')
                            ->select('t01')
                            // ->addSelect('t02')
                            ->addSelect('t01.id AS id, t01.codigoDonante as codigo_donante')
                            ->addSelect('UPPER(CONCAT(t01.primerApellido, \' \', COALESCE(t01.segundoApellido, \'\'), \', \', t01.primerNombre, \' \', COALESCE(t01.segundoNombre, \'\'), \' -- | -- ( \', t01.codigoDonante, \' )\')) AS full_name')
                            ->from('MinsalSiblhBundle:BlhDonante', 't01')
                            // ->innerJoin('t01.idPaciente', 't02')
                            // ->where('t01.idEstablecimiento = :id_est')
                            // ->setParameter('id_est', $localeId)
                            ->orderBy('t01.codigoDonante')
                            ->addOrderBy('full_name')
                            ->distinct()
                            ->setMaxResults(25);

        if ($t === 'blh') {
        	$query->andWhere('t01.idBancoDeLeche = :id_est')
                            ->setParameter('id_est', $localeId);
        }
        elseif ($t === 'ctr') {
        	$query->andWhere('t01.idCentroRecoleccion = :id_est')
                            ->setParameter('id_est', $localeId);
        }

        if (is_numeric(str_replace(array('-', 'D'), '', $q))) {
            $query->andWhere($query->expr()->like('LOWER(t01.codigoDonante)', ':donor_code'))
                                ->setParameter('donor_code', /*'%' .*/ strtolower($q) . '%');
        } else {
            $query->andWhere($query->expr()->like('LOWER(CONCAT(t01.primerApellido, COALESCE(t01.segundoApellido, \'\'), t01.primerNombre, COALESCE(t01.segundoNombre, \'\')))', ':donor_code'))
                                ->setParameter('donor_code', '%' . strtolower(str_replace(' ', '', $q)) . '%');
        }

        return $query->getQuery()->getScalarResult();
    }

    /////////////////////////////////////////////////////////////////////////////////////
    //////// SEARCH BY ID METHOD
    /////////////////////////////////////////////////////////////////////////////////////
    public function searchById($localeId, $t, $id)
    {
        ////////////////////////////////////////
        //////// donor is local
        ////////////////////////////////////////
        $query = $this->getEntityManager()
                    ->createQueryBuilder('t01')
                            ->select('t01')
                            // ->addSelect('t02', 't03')
                            ->addSelect('t01.id AS id, t01.codigoDonante as codigo_donante')
                            ->addSelect('UPPER(CONCAT(t01.primerApellido, \' \', COALESCE(t01.segundoApellido, \'\'), \', \', t01.primerNombre, \' \', COALESCE(t01.segundoNombre, \'\'), \' -- | -- ( \', t01.codigoDonante, \' )\')) AS full_name')
                            ->addSelect('UPPER(CONCAT(t01.primerApellido, \' \', COALESCE(t01.segundoApellido, \'\'), \', \', t01.primerNombre, \' \', COALESCE(t01.segundoNombre, \'\'))) AS whole_name')
                            ->from('MinsalSiblhBundle:BlhDonante', 't01')
                            // ->innerJoin('t01.idPaciente', 't02')
                            // ->innerJoin('t02.idSexo', 't03')
                            // ->where('t01.idEstablecimiento = :id_est')
                            // ->setParameter('id_est', $localeId)
                            ->andWhere('t01.id = :id')
                            ->setParameter('id', $id);

        if ($t === 'blh') {
        	$query->andWhere('t01.idBancoDeLeche = :id_est')
                            ->setParameter('id_est', $localeId);
        }
        elseif ($t === 'ctr') {
        	$query->andWhere('t01.idCentroRecoleccion = :id_est')
                            ->setParameter('id_est', $localeId);
        }

        return $query->getQuery()->getScalarResult();
    }

}