<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhEgresoReceptorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhEgresoReceptorRepository extends \Doctrine\ORM\EntityRepository
{
}
