<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhFrascoRecolectadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhFrascoRecolectadoRepository extends \Doctrine\ORM\EntityRepository
{
}
