<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhFrascoProcesadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhFrascoProcesadoRepository extends \Doctrine\ORM\EntityRepository
{
}
