<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhHistoriaActualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhHistoriaActualRepository extends \Doctrine\ORM\EntityRepository
{
}
