<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhHistorialClinicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhHistorialClinicoRepository extends \Doctrine\ORM\EntityRepository
{
}
