<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhLoteAnalisisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhLoteAnalisisRepository extends \Doctrine\ORM\EntityRepository
{
}
