<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhPasteurizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhPasteurizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
