<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhReceptorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhReceptorRepository extends \Doctrine\ORM\EntityRepository
{
}
