<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhSolicitudRepository extends \Doctrine\ORM\EntityRepository
{
}
