<?php

namespace Minsal\SiblhBundle\Repository;

/**
 * BlhSeguimientoReceptorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlhSeguimientoReceptorRepository extends \Doctrine\ORM\EntityRepository
{
}
