services:
    minsal_siblh.admin.blh_acidez:
        class: Minsal\SiblhBundle\Admin\BlhAcidezAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhAcidez, MinsalSiblhBundle:BlhAcidezAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhAcidez}

    minsal_siblh.admin.blh_donante:
        class: Minsal\SiblhBundle\Admin\BlhDonanteAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhDonante, MinsalSiblhBundle:BlhDonanteAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhDonante}

    minsal_siblh.admin.blh_historial_clinico:
        class: Minsal\SiblhBundle\Admin\BlhHistorialClinicoAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhHistorialClinico, MinsalSiblhBundle:BlhHistorialClinicoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhHistorialClinico}

    minsal_siblh.admin.ctl_centro_recoleccion:
        class: Minsal\SiblhBundle\Admin\CtlCentroRecoleccionAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\CtlCentroRecoleccion, MinsalSiblhBundle:CtlCentroRecoleccionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: CtlCentroRecoleccion}

    minsal_siblh.admin.blh_frasco_procesado_solicitud:
        class: Minsal\SiblhBundle\Admin\BlhFrascoProcesadoSolicitudAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhFrascoProcesadoSolicitud, MinsalSiblhBundle:BlhFrascoProcesadoSolicitudAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhFrascoProcesadoSolicitud}

    minsal_siblh.admin.blh_estado:
        class: Minsal\SiblhBundle\Admin\BlhEstadoAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhEstado, MinsalSiblhBundle:BlhEstadoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhEstado}

    minsal_siblh.admin.blh_bitacora:
        class: Minsal\SiblhBundle\Admin\BlhBitacoraAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhBitacora, MinsalSiblhBundle:BlhBitacoraAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhBitacora}

    minsal_siblh.admin.blh_pasteurizacion:
        class: Minsal\SiblhBundle\Admin\BlhPasteurizacionAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhPasteurizacion, MinsalSiblhBundle:BlhPasteurizacionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhPasteurizacion}

    minsal_siblh.admin.blh_examen_donante:
        class: Minsal\SiblhBundle\Admin\BlhExamenDonanteAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhExamenDonante, MinsalSiblhBundle:BlhExamenDonanteAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhExamenDonante}

    minsal_siblh.admin.blh_informacion_publica:
        class: Minsal\SiblhBundle\Admin\BlhInformacionPublicaAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhInformacionPublica, MinsalSiblhBundle:BlhInformacionPublicaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhInformacionPublica}

    minsal_siblh.admin.blh_analisis_microbiologico:
        class: Minsal\SiblhBundle\Admin\BlhAnalisisMicrobiologicoAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhAnalisisMicrobiologico, MinsalSiblhBundle:BlhAnalisisMicrobiologicoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhAnalisisMicrobiologico}

    minsal_siblh.admin.blh_lote_analisis:
        class: Minsal\SiblhBundle\Admin\BlhLoteAnalisisAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhLoteAnalisis, MinsalSiblhBundle:BlhLoteAnalisisAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhLoteAnalisis}

    minsal_siblh.admin.blh_solicitud:
        class: Minsal\SiblhBundle\Admin\BlhSolicitudAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhSolicitud, MinsalSiblhBundle:BlhSolicitudAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhSolicitud}

    minsal_siblh.admin.blh_rol:
        class: Minsal\SiblhBundle\Admin\BlhRolAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhRol, MinsalSiblhBundle:BlhRolAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhRol}

    minsal_siblh.admin.blh_historia_actual:
        class: Minsal\SiblhBundle\Admin\BlhHistoriaActualAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhHistoriaActual, MinsalSiblhBundle:BlhHistoriaActualAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhHistoriaActual}

    minsal_siblh.admin.blh_grupo_solicitud:
        class: Minsal\SiblhBundle\Admin\BlhGrupoSolicitudAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhGrupoSolicitud, MinsalSiblhBundle:BlhGrupoSolicitudAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhGrupoSolicitud}

    minsal_siblh.admin.blh_personal:
        class: Minsal\SiblhBundle\Admin\BlhPersonalAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhPersonal, MinsalSiblhBundle:BlhPersonalAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhPersonal}

    minsal_siblh.admin.blh_seguimiento_receptor:
        class: Minsal\SiblhBundle\Admin\BlhSeguimientoReceptorAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhSeguimientoReceptor, MinsalSiblhBundle:BlhSeguimientoReceptorAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhSeguimientoReceptor}

    minsal_siblh.admin.blh_banco_de_leche:
        class: Minsal\SiblhBundle\Admin\BlhBancoDeLecheAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhBancoDeLeche, MinsalSiblhBundle:BlhBancoDeLecheAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhBancoDeLeche}

    minsal_siblh.admin.blh_menu:
        class: Minsal\SiblhBundle\Admin\BlhMenuAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhMenu, MinsalSiblhBundle:BlhMenuAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhMenu}

    minsal_siblh.admin.blh_curva:
        class: Minsal\SiblhBundle\Admin\BlhCurvaAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhCurva, MinsalSiblhBundle:BlhCurvaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhCurva}

    minsal_siblh.admin.blh_crematocrito:
        class: Minsal\SiblhBundle\Admin\BlhCrematocritoAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhCrematocrito, MinsalSiblhBundle:BlhCrematocritoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhCrematocrito}

    minsal_siblh.admin.blh_analisis_sensorial:
        class: Minsal\SiblhBundle\Admin\BlhAnalisisSensorialAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhAnalisisSensorial, MinsalSiblhBundle:BlhAnalisisSensorialAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhAnalisisSensorial}

    minsal_siblh.admin.blh_temperatura_enfriamiento:
        class: Minsal\SiblhBundle\Admin\BlhTemperaturaEnfriamientoAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhTemperaturaEnfriamiento, MinsalSiblhBundle:BlhTemperaturaEnfriamientoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhTemperaturaEnfriamiento}

    minsal_siblh.admin.blh_receptor:
        class: Minsal\SiblhBundle\Admin\BlhReceptorAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhReceptor, MinsalSiblhBundle:BlhReceptorAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhReceptor}

    minsal_siblh.admin.blh_frasco_procesado:
        class: Minsal\SiblhBundle\Admin\BlhFrascoProcesadoAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhFrascoProcesado, MinsalSiblhBundle:BlhFrascoProcesadoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhFrascoProcesado}

    minsal_siblh.admin.blh_temperatura_pasteurizacion:
        class: Minsal\SiblhBundle\Admin\BlhTemperaturaPasteurizacionAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhTemperaturaPasteurizacion, MinsalSiblhBundle:BlhTemperaturaPasteurizacionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhTemperaturaPasteurizacion}

    minsal_siblh.admin.blh_rol_menu:
        class: Minsal\SiblhBundle\Admin\BlhRolMenuAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhRolMenu, MinsalSiblhBundle:BlhRolMenuAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhRolMenu}

    minsal_siblh.admin.blh_egreso_receptor:
        class: Minsal\SiblhBundle\Admin\BlhEgresoReceptorAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhEgresoReceptor, MinsalSiblhBundle:BlhEgresoReceptorAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhEgresoReceptor}

    minsal_siblh.admin.blh_examen:
        class: Minsal\SiblhBundle\Admin\BlhExamenAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhExamen, MinsalSiblhBundle:BlhExamenAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhExamen}

    minsal_siblh.admin.blh_frasco_recolectado:
        class: Minsal\SiblhBundle\Admin\BlhFrascoRecolectadoAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhFrascoRecolectado, MinsalSiblhBundle:BlhFrascoRecolectadoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhFrascoRecolectado}

    minsal_siblh.admin.blh_frasco_recolectado_frasco_p:
        class: Minsal\SiblhBundle\Admin\BlhFrascoRecolectadoFrascoPAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhFrascoRecolectadoFrascoP, MinsalSiblhBundle:BlhFrascoRecolectadoFrascoPAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhFrascoRecolectadoFrascoP}

    minsal_siblh.admin.blh_opcion_menu:
        class: Minsal\SiblhBundle\Admin\BlhOpcionMenuAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhOpcionMenu, MinsalSiblhBundle:BlhOpcionMenuAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhOpcionMenu}

    minsal_siblh.admin.blh_donacion:
        class: Minsal\SiblhBundle\Admin\BlhDonacionAdmin
        arguments: [~, Minsal\SiblhBundle\Entity\BlhDonacion, MinsalSiblhBundle:BlhDonacionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: BlhDonacion}
