<?php

namespace SanRafael\RequerimientosBundle\Repository;

/**
 * AreaTrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaTrabajoRepository extends \Doctrine\ORM\EntityRepository
{
}
