<?php

namespace SanRafael\RequerimientosBundle\Repository;

/**
 * AreaServicioAtencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaServicioAtencionRepository extends \Doctrine\ORM\EntityRepository
{
}
