<?php

namespace SanRafael\RequerimientosBundle\Repository;

/**
 * EmpleadoAreaServicioAtencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpleadoAreaServicioAtencionRepository extends \Doctrine\ORM\EntityRepository
{
}
