<?php

namespace SanRafael\RequerimientosBundle\Repository;

/**
 * EmpleadoAreaServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpleadoAreaServicioRepository extends \Doctrine\ORM\EntityRepository
{
}
