<?php

namespace SanRafael\RequerimientosBundle\Repository;

/**
 * MarcaEquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarcaEquipoRepository extends \Doctrine\ORM\EntityRepository
{
}
