<?php

namespace SanRafael\RequerimientosBundle\Repository;

/**
 * ModeloEquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeloEquipoRepository extends \Doctrine\ORM\EntityRepository
{
}
