<?php

namespace SanRafael\RequerimientosBundle\Repository;

/**
 * RequerimientoEmpleadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequerimientoEmpleadoRepository extends \Doctrine\ORM\EntityRepository
{
}
