<?php

namespace SanRafael\RequerimientosBundle\Repository;

/**
 * RequerimientoTrabajoRequeridoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequerimientoTrabajoRequeridoRepository extends \Doctrine\ORM\EntityRepository
{
}
