<?php

namespace SanRafael\RequerimientosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServicioAtencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioAtencionRepository extends EntityRepository
{
}
