<?php

namespace SanRafael\RequerimientosBundle\Repository;

/**
 * SolucionRequerimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolucionRequerimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
