<?php

namespace SanRafael\RequerimientosBundle\Repository;

/**
 * TrabajoRequeridoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrabajoRequeridoRepository extends \Doctrine\ORM\EntityRepository
{
}
