sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
    title:       Sistema de Bancos de Leche Humana
    title_logo:  /bundles/minsalsiblh/images/blh.png
    templates:
        # default global templates
        layout:  SonataAdminBundle:Blh:standard_layout.html.twig
        ajax:    SonataAdminBundle:Blh:ajax_layout.html.twig
 
        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
 
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
 
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
    options:
        form_type: horizontal
        html5_validate: false
