<?php

namespace Minsal\SiapsBundle\Repository;

/**
 * CtlEstablecimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CtlEstablecimientoRepository extends \Doctrine\ORM\EntityRepository
{
}