<?php

namespace Minsal\SiapsBundle\Repository;

/**
 * MntExpedienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MntExpedienteRepository extends \Doctrine\ORM\EntityRepository
{
}
