<?php

namespace Minsal\SiapsBundle\Repository;

/**
 * MntEmpleadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MntEmpleadoRepository extends \Doctrine\ORM\EntityRepository
{
}
