<?php

namespace Minsal\SiapsBundle\Repository;

/**
 * MntPacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MntPacienteRepository extends \Doctrine\ORM\EntityRepository
{
}
