services:
    san_rafael_requerimientos.admin.req_ctl_equipo:
        class: SanRafael\RequerimientosBundle\Admin\ReqCtlEquipoAdmin
        arguments: [~, SanRafael\RequerimientosBundle\Entity\ReqCtlEquipo, SanRafaelRequerimientosBundle:ReqCtlEquipoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ReqCtlEquipo}

#    san_rafael_requerimientos.admin.req_requerimiento:
#        class: SanRafael\RequerimientosBundle\Admin\ReqRequerimientoAdmin
#        arguments: [~, SanRafael\RequerimientosBundle\Entity\ReqRequerimiento, SanRafaelRequerimientosBundle:ReqRequerimientoAdmin]
#        tags:
#            - {name: sonata.admin, manager_type: orm, group: admin, label: ReqRequerimiento}

    san_rafael_requerimientos.admin.req_ctl_area_trabajo:
        class: SanRafael\RequerimientosBundle\Admin\ReqCtlAreaTrabajoAdmin
        arguments: [~, SanRafael\RequerimientosBundle\Entity\ReqCtlAreaTrabajo, SanRafaelRequerimientosBundle:ReqCtlAreaTrabajoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ReqCtlAreaTrabajo}

    san_rafael_requerimientos.admin.req_ctl_marca_equipo:
        class: SanRafael\RequerimientosBundle\Admin\ReqCtlMarcaEquipoAdmin
        arguments: [~, SanRafael\RequerimientosBundle\Entity\ReqCtlMarcaEquipo, SanRafaelRequerimientosBundle:ReqCtlMarcaEquipoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ReqCtlMarcaEquipo}

    san_rafael_requerimientos.admin.req_ctl_modelo_equipo:
        class: SanRafael\RequerimientosBundle\Admin\ReqCtlModeloEquipoAdmin
        arguments: [~, SanRafael\RequerimientosBundle\Entity\ReqCtlModeloEquipo, SanRafaelRequerimientosBundle:ReqCtlModeloEquipoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ReqCtlModeloEquipo}

    san_rafael_requerimientos.admin.req_ctl_solucion_requerimiento:
        class: SanRafael\RequerimientosBundle\Admin\ReqCtlSolucionRequerimientoAdmin
        arguments: [~, SanRafael\RequerimientosBundle\Entity\ReqCtlSolucionRequerimiento, SanRafaelRequerimientosBundle:ReqCtlSolucionRequerimientoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ReqCtlSolucionRequerimiento}

    san_rafael_requerimientos.admin.req_ctl_tipo_equipo:
        class: SanRafael\RequerimientosBundle\Admin\ReqCtlTipoEquipoAdmin
        arguments: [~, SanRafael\RequerimientosBundle\Entity\ReqCtlTipoEquipo, SanRafaelRequerimientosBundle:ReqCtlTipoEquipoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ReqCtlTipoEquipo}

    san_rafael_requerimientos.admin.req_empleado:
        class: SanRafael\RequerimientosBundle\Admin\ReqEmpleadoAdmin
        arguments: [~, SanRafael\RequerimientosBundle\Entity\ReqEmpleado, SanRafaelRequerimientosBundle:ReqEmpleadoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ReqEmpleado}

    san_rafael_requerimientos.admin.req_empleado_area_servicio_atencion:
        class: SanRafael\RequerimientosBundle\Admin\ReqEmpleadoAreaServicioAtencionAdmin
        arguments: [~, SanRafael\RequerimientosBundle\Entity\ReqEmpleadoAreaServicioAtencion, SanRafaelRequerimientosBundle:ReqEmpleadoAreaServicioAtencionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ReqEmpleadoAreaServicioAtencion}

#    san_rafael_requerimientos.admin.req_requerimiento:
#        class: SanRafael\RequerimientosBundle\Admin\ReqRequerimientoAdmin
#        arguments: [~, SanRafael\RequerimientosBundle\Entity\ReqRequerimiento, SanRafaelRequerimientosBundle:ReqRequerimientoAdmin]
#        tags:
#            - {name: sonata.admin, manager_type: orm, group: admin, label: ReqRequerimiento}

    san_rafael_requerimientos.admin.req_requerimiento:
        class: SanRafael\RequerimientosBundle\Admin\ReqRequerimientoAdmin
        arguments: [~, SanRafael\RequerimientosBundle\Entity\ReqRequerimiento, SanRafaelRequerimientosBundle:ReqRequerimientoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ReqRequerimiento}
